apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "backend.name" . }}
  ports:
    - port: 5000
      targetPort: 5000

